# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 274)
        MainWindow.setWindowIcon(QtGui.QIcon('vkontakte.ico'))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 615, 207))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Status = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Status.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255, 20%);\n"
"font-size: 30px;\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.Status.setAlignment(QtCore.Qt.AlignCenter)
        self.Status.setObjectName("Status")
        self.gridLayout_2.addWidget(self.Status, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255, 20%);\n"
"font-size: 30px;\n"
"text-align: center;\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 2, 0, 1, 1)
        self.Done = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Done.sizePolicy().hasHeightForWidth())
        self.Done.setSizePolicy(sizePolicy)
        self.Done.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Done.setFont(font)
        self.Done.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Done.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 0, 0, 20%);")
        self.Done.setObjectName("Done")
        self.gridLayout_2.addWidget(self.Done, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 26))
        self.menubar.setObjectName("menubar")
        self.Menu = QtWidgets.QAction(self.menubar)
        self.Menu.setObjectName("Menu")
        self.Help = QtWidgets.QAction(self.menubar)
        self.Help.setObjectName("Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.Menu)
        self.menubar.addAction(self.Help)

        self.HelpBox = QtWidgets.QLabel(self.scrollAreaWidgetContents)

        self.HelpBox.setStyleSheet("border-radius: 20px;\n"
                                  "background-color: rgb(255, 255, 255, 20%);\n"
                                  "font-size: 30px;\n"
                                  "text-align: center;\n"
                                  "color: rgb(0, 0, 0);")
        self.HelpBox.setAlignment(QtCore.Qt.AlignCenter)
        self.HelpBox.setObjectName("HelpBox")
        self.HelpBox.hide()
        self.gridLayout_2.addWidget(self.HelpBox, 0, 0, 1, 1)

        self.Events()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Накрутка шагов ВК"))
        self.Status.setText(_translate("MainWindow", "НАКРУТКА ШАГОВ ВК"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Введите необходимое количество шагов"))
        self.Done.setText(_translate("MainWindow", "Накрутить"))
        self.Menu.setText(_translate("MainWindow", "Накрутка"))
        self.Help.setText(_translate("MainWindow", "Помощь"))
        self.HelpBox.setText(_translate("MainWindow", "Введите своё количество шагов и нажмите Накрутить"))

    def Events(self):
        self.Done.clicked.connect(self.Page1)
        self.Menu.triggered.connect(lambda: self.Page1())
        self.Help.triggered.connect(lambda: self.Page2())

    def Page2(self):
        self.textEdit.hide()
        self.Done.hide()
        self.Status.hide()
        self.HelpBox.show()

    def Page1(self):
        self.textEdit.show()
        self.Done.show()
        self.Status.show()
        self.HelpBox.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
